### PR TITLE
[HOTFIX] Fixed docs build

### PR DESCRIPTION
**Pull request by e-kolpakov**
**Description:** Fixes CHANGELOG format (and CI build)

**Merge deadline:** ASAP - build is broken on master.

**Testing instructions:**

`make docs` passes and CI build is green 

**Reviewers:**
- [x] @mtyaka 
- [x] @mattdrayer 

**Merge checklist:**
- [x] All reviewers approved
- [x] CI build is green
- [x] ~~Version bumped~~ N/A
- [x] ~~Changelog record added~~ N/A
- [x] ~~Documentation updated (not only docstrings)~~ N/A
- [x] Commits are (reasonably) squashed
- [x] ~~Translations are updated~~ N/A
- [x] PR author is listed in AUTHORS

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @e-kolpakov! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fedx-enterprise&number=45"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by e-kolpakov** [comment]
@mattdrayer @mtyaka Please review this really tiny PR ASAP - we've got broken build on master.

**Comment by mtyaka** [comment]
👍 verified that `make docs` fails on master and succeeds on this branch.

**Comment by mattdrayer** [comment]
👍 quick, fix it!  😄

**Pull request merged**
