### PR TITLE
Updated pypi deployment secret

### PR DESCRIPTION
**Pull request by kylecrawshaw**
@e-kolpakov I've updated the secrets just to make sure I didn't do it incorrectly the first time. As soon as this is merged to master it should attempt to deploy again.

### CODE REVIEW

**Comment by clintonb** [comment]
I don't believe the credentials are the problem. The creation/first release of the package needs to be done manually. Travis won't create new packages. https://pypi.python.org/pypi/edx-enterprise

**Comment by kylecrawshaw** [comment]
Thanks @clintonb. I didn't realize that was the case!

**Comment by clintonb** [comment]
No worries. I see now that this information is not on the wiki page at https://openedx.atlassian.net/wiki/display/OpenOPS/Publishing+a+Package+to+PyPI+using+Travis.

**Comment by kylecrawshaw** [comment]
I created the PKG_INFO and uploaded that to PyPi. It should be good to go. Closing out this PR now. Thanks @clintonb!

@e-kolpakov — On next commit to master, let's see what happens.

**Pull request closed without merging**
