### PR TITLE
Add from email address to enrollment notification template model

### PR DESCRIPTION
**Pull request by tuchfarber**
**Description:** Adds from_email_address to the email notification template so we can customize the email per enterprise. Defaults to `settings.DEFAULT_FROM_EMAIL`. 

**JIRA:** https://openedx.atlassian.net/browse/WL-1373

**Dependencies:** None

**Merge deadline:** Soon?

**Installation instructions:** N/A

**Testing instructions:**

1. Migrate migrations
2. Add enterprise enrollment notification template http://localhost:18000/admin/enterprise/enrollmentnotificationemailtemplate/add/ 
3. Set from_email_address
4. Add a learner to a enterprise/course via "Manage Learners" http://localhost:18000/admin/enterprise/enterprisecustomer/<ENTERPRISE_UUID>/manage_learners
5. See new email address in email log

**Merge checklist:**

- [x] Check that the versions of the requirements in the `platform-master.in` file match edx-platform.
- [x] New requirements are in the right place (`base.in` if only used in enterprise; in the correct `platform-****.in` files if they're hosted in edx-platform)
- [x] Regenerate requirements with `make upgrade && make requirements` (and make sure to fix any errors).
  **DO NOT** just add dependencies to `requirements/*.txt` files.
- [x] Called `make static` for webpack bundling if any static content was updated.
- [x] All reviewers approved
- [x] CI build is green
- [x] Version bumped
- [x] Changelog record added
- [x] Documentation updated (not only docstrings)
- [ ] Commits are (reasonably) squashed
- [ ] Translations are updated
- [ ] PR author is listed in AUTHORS

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is finished.
- [ ] Delete working branch (if not needed anymore)
- [ ] edx-platform PR (be sure to include edx-platform requirements upgrades that were present in this PR)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

### CODE REVIEW

**Comment by tuchfarber** [comment]
Whoops. Forgot to add versioning.

**Comment by tuchfarber** [comment]
@douglashall From what I understand, the from email address needs to be edited per enterprise, not per site. I think they want Boeing customers to get an email from an address that has Boeing in it. Perhaps @bill-filler could chime in. I can swap it over to a 1 per site, but the ticket requested 1 per enterprise.

**Comment by douglashall** [comment]
@tuchfarber Hmm, it looks like the Jira ticket does not call for per-enterprise customization. We should sort that out before moving forward. My concern is that this makes it easy for someone to add an email address in Django admin without first verifying it through Amazon SES.

**Comment by tuchfarber** [comment]
@douglashall I was basing it off the title of the ticket "from email needs to be customized per enterprise". But I see what you mean. Hopefully @bill-filler can clarify. I think @fredsmith said in standup today that if we're sending from LMS we can send whatever we want. It's only from Jenkins that we have to do configuration.

**Comment by bill-filler** [comment]
I added a comment to the Jira ticket last week after talking to Jennifer that per-site is probably fine

**Comment by tuchfarber** [comment]
:( Will fix.

**Comment by tuchfarber** [comment]
@douglashall Could I get some historical context on `email_from_address` and `DEFAULT_FROM_EMAIL` in site config?

**Comment by douglashall** [comment]
@tuchfarber I think that's the product of multiple engineers not being in sync. I have tried to be consistent with using `DEFAULT_FROM_EMAIL` wherever I have the opportunity to.

**Comment by tuchfarber** [comment]
@douglashall Now that the email is based on site config, can I get another review?

**Pull request merged**
