### PR TITLE
[ENT-618] Put view tests into separate files. (tech debt)

### PR DESCRIPTION
**Pull request by UmanShahzad**
**Description:** This PR puts test classes that were in `tests/test_views.py` into separate files, depending on which class they were specifically testing.

**JIRA:** [ENT-618](https://openedx.atlassian.net/browse/ENT-618)

**Dependencies:** Currently based on the huge amount of tests that were added as part of ENT-486.

**Merge deadline:** Whenever.

**Testing instructions:**

1. This only puts tests into separate files to make it easier to manage, modify, add, and delete view tests. So just make sure the travis build is passing.

**Merge checklist:**

- [ ] Check that the versions of the requirements in the `platform-master.in` file match edx-platform.
- [ ] New requirements are in the right place (`base.in` if only used in enterprise; in the correct `platform-****.in` files if they're hosted in edx-platform)
- [ ] Regenerate requirements with `make upgrade && make requirements` (and make sure to fix any errors).
  **DO NOT** just add dependencies to `requirements/*.txt` files.
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are (reasonably) squashed
- [ ] Translations are updated
- [ ] PR author is listed in AUTHORS

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is finished.
- [ ] Delete working branch (if not needed anymore)
- [ ] edx-platform PR (be sure to include edx-platform requirements upgrades that were present in this PR)

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @UmanShahzad! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=177&repo=edx%2Fedx-enterprise"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by UmanShahzad** [comment]
@haikuginger Ready for your review.

@douglashall If you could eye this real quick, too, that'd be great -- it's a simple change, helps us organizationally later for new apps to come.

**Comment by UmanShahzad** [comment]
P.S. I didn't version bump this, sorry about that. Since it doesn't introduce any new functionality or even any new code I suppose it doesn't matter. We'll just version bump for #171.

**Comment by douglashall** [comment]
@UmanShahzad Sounds like a plan on the version bump.

**Pull request merged**
