### PR TITLE
Update consent API to use catalog service user; fix coverage on master

### PR DESCRIPTION
**Pull request by haikuginger**
**Description:**

This pull request has two major features:

1. Switch the consent API over to use `CourseCatalogApiServiceClient` class, which populates with a token from the system catalog service user, rather than from the user for a given request. This solves for an issue where non-privileged users encountered authorization errors for the Data Sharing Consent API.

2. Fix missing coverage on the master branch

**JIRA:** No relevant JIRA

**Dependencies:** None

**Merge deadline:** ASAP

**Installation instructions:**

1. Ensure devstack is configured with course discovery
2. Ensure a catalog is created in course discovery
3. Ensure EnterpriseCustomer is linked to the given catalog

**Testing instructions:**

1. Using edx-enterprise master (not this branch), log in with a non-privileged user, and access the consent URL following the pattern:
    ```
    http://localhost:18000/consent/api/v1/data_sharing_consent?username=unpriv_user&enterprise_customer_uuid=ent-uuid-here&course_id=course-v1:edX%2BDemoX%2BDemo_Course
    ```
2. Verify that a 400-series authorization error occurs.
3. Pull this branch and restart the LMS
4. Refresh the aforementioned URL and verify that no error occurs.

**Merge checklist:**

- [ ] Check that the versions of the requirements in the `platform-master.in` file match edx-platform.
- [ ] New requirements are in the right place (`base.in` if only used in enterprise; in the correct `platform-****.in` files if they're hosted in edx-platform)
- [ ] Regenerate requirements with `make upgrade && make requirements` (and make sure to fix any errors).
  **DO NOT** just add dependencies to `requirements/*.txt` files.
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are (reasonably) squashed
- [ ] Translations are updated
- [ ] PR author is listed in AUTHORS

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is finished.
- [ ] Delete working branch (if not needed anymore)
- [ ] edx-platform PR (be sure to include edx-platform requirements upgrades that were present in this PR)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @haikuginger! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fedx-enterprise&number=174"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by UmanShahzad** [comment]
@haikuginger Code changes look good, am testing now.

**Comment by UmanShahzad** [comment]
@haikuginger Thanks a lot for the coverage too btw!

**Comment by haikuginger** [comment]
Final changes made and rebased from 6effc46. @UmanShahzad, you'll need to rebase #168 and make a couple small tweaks to `enterprise/views.py` and `test/test_views.py` once this is merged.

**Comment by UmanShahzad** [comment]
@haikuginger Thanks, I will do that :+1:

**Pull request merged**
