### PR TITLE
Decrease SAPSF chunk size from 1000 to 500

### PR DESCRIPTION
**Pull request by mattdrayer**
Per SAP technical support, while the SuccessFactors Learning API does support payloads up to 1000 records per request, this is too much data for most tenants to handle in a single request.  SAPSF recommends sending no more than 500 records per request.

### CODE REVIEW

**Comment by mattdrayer** [comment]
@georgebabey I included the version bump for this PR -- good to go?

**Comment by georgebabey** [comment]
Looks good - :shipit:

**Comment by douglashall** [comment]
Have we stopped using CHANGELOG.rst?

**Comment by mattdrayer** [comment]
:man_shrugging: -- I can updated if we are still using it

**Comment by georgebabey** [comment]
I like it - shows in PyPi. For a change this small most probably wouldn't care but then they'll be left wondering *what* changed

**Comment by mattdrayer** [comment]
Went ahead and added a changelog entry

**Pull request merged**
