### PR TITLE
Revert "Tuchfarber/enterprise email template 1"

### PR DESCRIPTION
**Pull request by UmanShahzad**
Reverts edx/edx-enterprise#199

It was unsquashed/no changelog/no version bump.

@douglashall I also think we should merge the original PR only after we merge #198 otherwise that could cause issues in merging that migration on Tuesday.

cc @tuchfarber

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @UmanShahzad! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fedx-enterprise&number=200"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by UmanShahzad** [comment]
@tuchfarber No worries :)

**Comment by UmanShahzad** [comment]
@tuchfarber Just make sure to open another PR for this :+1:

**Comment by douglashall** [comment]
@tuchfarber @UmanShahzad I merged https://github.com/edx/edx-enterprise/pull/198. You should be clear to reintroduce this work.

**Pull request merged**
