### PR TITLE
ENT-678 Fix enterprise logo stretching in enterprise sidebar

### PR DESCRIPTION
**Pull request by zubair-arbi**
@asadiqbal08 @saleem-latif 

**Description:** Fix enterprise logo stretching issue in enterprise sidebar on course/program enrollment pages.

**JIRA:** [ENT-678](https://openedx.atlassian.net/browse/ENT-678)

**Dependencies:** N/A

**Merge deadline:** 15-1-2018

**Installation instructions:** Install edx-enterprise from this branch `zub/ENT-678-fix-enterprise-logo-streching` in `edx-platform`.

**Testing instructions:**

1. Create an enterprise with a logo.
2. As an enterprise learner login (from enterprise related SSO) and go to course enrollment page.
3. Verify that the enterprise logo is not stretched vertically. Max height and max width of enterprise logo will be `150px`.

**Merge checklist:**

- [ ] Check that the versions of the requirements in the `platform-master.in` file match edx-platform.
- [ ] New requirements are in the right place (`base.in` if only used in enterprise; in the correct `platform-****.in` files if they're hosted in edx-platform)
- [ ] Regenerate requirements with `make upgrade && make requirements` (and make sure to fix any errors).
  **DO NOT** just add dependencies to `requirements/*.txt` files.
- [ ] Called `make static` for webpack bundling if any static content was updated.
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are (reasonably) squashed
- [ ] Translations are updated
- [ ] PR author is listed in AUTHORS

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is finished.
- [ ] Delete working branch (if not needed anymore)
- [ ] edx-platform PR (be sure to include edx-platform requirements upgrades that were present in this PR)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

### CODE REVIEW

**Comment by zubair-arbi** [comment]
@saleem-latif @asadiqbal08 @mattdrayer please review. You can verify the change on business sandbox: https://business.sandbox.edx.org/enterprise/2b5a2956-7746-4fc9-9587-bc887ba45973/course/course-v1%3AedX%2BTest101%2Bcourse/enroll/

**Comment by asadiqbal08** [comment]
need to add changelog + version bump

**Comment by zubair-arbi** [comment]
@georgebabey Please have a look.

**Comment by zubair-arbi** [comment]
I am merging this as I have verified on business sandbox that the logo vertical stretching is fixed with this change.

**Pull request merged**
