### PR TITLE
ENT-452 Enforce data sharing consent at login for SSO users iff data sharing consent is requested AT_LOGIN

### PR DESCRIPTION
**Pull request by pomegranited**
**Description:** When signing in via SSO for an Enterprise customer who requires data sharing consent, this consent should only be required at login if the consent required is `AT_LOGIN`.  All other consent requirements (`AT_ENROLLMENT`, `OPTIONAL`, `EXTERNALLY_MANAGED`) will be handled at a later time.

**JIRA:** [ENT-452](https://openedx.atlassian.net/browse/ENT-452)

**Dependencies:** None.

**Merge deadline:** 04/Jul/17

**Installation instructions:**

Standard Enterprise Customer setup, with TPA/SSO enabled.

**Sandbox**

Deployed to https://business.sandbox.edx.org, and:

LMS: https://pr15359-2.sandbox.opencraft.hosting
Studio: https://studio-pr15359-2.sandbox.opencraft.hosting

**Testing instructions:**

1. As `staff` via [LMS Admin](https://pr15359-2.sandbox.opencraft.hosting/admin/enterprise/enterprisecustomer/), ensure that the `EnterpriseCustomer` is set to:
    1. Enable data sharing consent
    1. Require consent `at login`
1. Ensure that no data sharing consent has been granted for the learner you'll be using, or that no `EnterpriseCustomerUser` record exists for that learner.
1. Visit the [login page](https://pr15359-2.sandbox.opencraft.hosting/login), and click the `TestShib` button to login via SSO.  On the sandbox, I've registered the testshib `superego` user.
1. Ensure that Data Consent Sharing page is shown after the TestShib login screen.  Do not grant consent yet.
1. Logout of the TestShib/learner session.
1. As `staff` via [LMS Admin](https://pr15359-2.sandbox.opencraft.hosting/admin/enterprise/enterprisecustomer/), update the `EnterpriseCustomer` to:
    1. Enable data sharing consent
    1. Require consent `at enrollment`
1. Repeat Step 3.  Note that no Data Consent Sharing page is shown during the SSO login process. 

**Merge checklist:**

- [x] Regenerate requirements with `make upgrade && make requirements` (and make sure to fix any errors).
  **DO NOT** just add dependencies to `requirements/*.txt` files.
- [x] All reviewers approved
- [x] CI build is green
- [x] Version bumped
- [x] Changelog record added
- [x] <strike>Documentation updated (not only docstrings)</strike> Bugfix, no need to update docs.
- [x] Commits are (reasonably) squashed
- [x] <strike>Translations are updated</strike> - user-facing strings untouched.
- [x] PR author is listed in AUTHORS

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is finished.
- [ ] Delete working branch (if not needed anymore)

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @pomegranited! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=131&repo=edx%2Fedx-enterprise"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by haikuginger** [comment]
Code looks good to me; I'll test it on the sandbox and approve once it's available.

**Comment by haikuginger** [comment]
@pomegranited, can you rebase on master to make this branch compatible with the current edx-platform?

**Comment by pomegranited** [comment]
@haikuginger I've rebased, but my sandbox is now broken (`python-social-auth` issues).  I'm spawning a new appserver in the hope that the migrations will take care of the social auth upgrade, but may end up having to create a new sandbox instance altogether.

If you want you're welcome to test the changes manually on you devstack - the setup and test instructions should be sufficient.

**Comment by pomegranited** [comment]
@brittneyexline @haikuginger  Ok, at long last, I have a working sandbox!  Please note the updated URL in the description: https://pr15359-2.sandbox.opencraft.hosting

> I'd also like to test the behavior for an additional case, which is configuring the enforces data sharing consent setting to be 'at enrollment' and enabling the requires account level consent flag.

Yep, that should work fine.  However see below:

> we should check this behavior in the context of the enterprise landing page

We're having issues with our automatic SSL certificate generation, so https isn't working on my sandbox, and therefore neither is the enterprise landing page, since it hits its own Course API via https, e.g. this URL 500s (trace below):

https://pr15359-2.sandbox.opencraft.hosting/enterprise/fa72e8af-104e-438b-be5b-c32e96e4d458/course/course-v1%3AedX%2BDemoX%2BDemo_Course/enroll/

Is there any way we can test this on your sandbox, or devstack, instead?

```
Jun 22 09:17:09 pr15359-2 [service_variant=lms][django.request][env:sandbox] ERROR [pr15359-2  432] [base.py:256] - Internal Server Error: /enterprise/fa72e8af-104e-438b-be5b-c32e96e4d458/course/course-v1:edX+DemoX+Demo_Course/enroll/
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/newrelic-2.78.0.57/newrelic/hooks/framework_django.py", line 503, in wrapper
    return wrapped(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/newrelic-2.78.0.57/newrelic/hooks/framework_django.py", line 885, in wrapper
    return wrapped(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/enterprise/utils.py", line 621, in wrapper
    return view(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/enterprise/views.py", line 878, in get
    enterprise_customer, course, modes = self.get_base_details(enterprise_uuid, course_id)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/enterprise/views.py", line 672, in get_base_details
    course_details = client.get_course_details(course_id)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/enterprise/lms_api.py", line 233, in get_course_details
    return self.client.courses(course_id).get()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/slumber/__init__.py", line 155, in get
    resp = self._request("GET", params=kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/slumber/__init__.py", line 97, in _request
    resp = self._store["session"].request(method, url, data=data, params=params, files=files, headers=headers)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/newrelic-2.78.0.57/newrelic/api/external_trace.py", line 124, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='pr15359-2.sandbox.opencraft.hosting', port=443): Max retries exceeded with url: /api/courses/v1/courses/course-v1:edX+DemoX+Demo_Course/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f866bf858d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by pomegranited** [comment]
@brittneyexline @haikuginger CC @itsjeyd  For testing this PR and https://github.com/edx/edx-enterprise/pull/137, I've created a merged branch, based on [current master (`0.36.4`)](https://github.com/edx/edx-enterprise/commit/11aa48a080404c86290c98372d468ad1056b6660): https://github.com/open-craft/edx-enterprise/tree/jill/ent-452%2Bent-460

However, I'm unable to ssh into `business.sandbox.edx.org` to install it - maybe [my github key](https://github.com/pomegranited.keys) isn't installed?  Or maybe I'm trying the wrong username?  I've tried everything I can think of (`pomegranited`, `jvogel`, `jill`, `ubuntu`, `edx`, `root`...).  Help?

**Comment by douglashall** [comment]
@pomegranited I have cherry-picked this commit onto a sprint branch (edx/edx-platform:mighty_mouse) and deployed that branch to https://business.sandbox.edx.org.

Also, I gave you ssh access to business.sandbox.edx.org. You should be able to access using your github username now.

**Comment by pomegranited** [comment]
Thank you, @douglashall !  I can shell in now.

**Comment by pomegranited** [comment]
Hi @brittneyexline , have you had a chance to test your use cases on the business sandbox?

**Comment by brittneyexline** [comment]
@pomegranited, the sandbox is in a weird state right now, I think because @douglashall is trying to fix something on it, so I wasn't able to look today. I will see if we can get to verifying this and other tickets for tomorrow.

**Comment by pomegranited** [comment]
Thanks @brittneyexline !  Let me know if there's anything I can do to help.

**Comment by pomegranited** [comment]
Thanks @douglashall ! @brittneyexline did you need to do more testing on this, or can I start on the merge checklist?

**Comment by itsjeyd** [comment]
@pomegranited We talked about this at standup -- it's ready to go :) Merging now.

CC @brittneyexline @douglashall

**Pull request merged**
