### PR TITLE
xAPI: Improve completion event logging.

### PR DESCRIPTION
**Pull request by mattdrayer**
**Merge checklist:**
- [ ] Any new requirements are in the right place (do **not** manually modify the `requirements/*.txt` files)
    - `base.in` if needed in production but edx-platform doesn't install it
    - `test-master.in` if edx-platform pins it, with a matching version
    - `make upgrade && make requirements` have been run to regenerate requirements
- [ ] `make static` has been run to update webpack bundling if any static content was updated
- [x] [Version](https://github.com/edx/edx-enterprise/blob/master/enterprise/__init__.py) bumped
- [x] [Changelog](https://github.com/edx/edx-enterprise/blob/master/CHANGELOG.rst) record added
- [ ] Translations updated

**Post merge:**
- [ ] Tag pushed and a new [version](https://github.com/edx/edx-enterprise/releases) released
- [ ] Version pushed to [PyPI](https://pypi.org/project/edx-enterprise/)
- [ ] PR created in [edx-platform](https://github.com/edx/edx-platform) to upgrade dependencies (including edx-enterprise)

### CODE REVIEW

**Comment by mattdrayer** [comment]
@ziafazal if you can please take a look at this PR and verify on DevStack that it works correctly, I would appreciate it.

**Comment by ziafazal** [comment]
@mattdrayer has made few changes to make it work on devstack. Could you please review?

**Comment by mattdrayer** [comment]
Thanks very much for validating @ziafazal -- the changes look good to me -- I have rebased/squashed everything and added the changelog and version bump.  Good to merge once automated checks pass?

**Comment by ziafazal** [comment]
@mattdrayer 👍

**Pull request merged**
