### PR TITLE
ENT-450 UAT Feedback: Enterprise Landing Page Styling

### PR DESCRIPTION
**Pull request by zubair-arbi**
@saleem-latif @asadiqbal08 @douglashall

**Description:** Styling feedback changes for enterprise course enrollment page
* Header and placement of PP statement are not same as on signing/register. (Here the PP statement Is a paragraph tag, which is right) "Welcome to edX" has disappeared. It should be identical.
* Confirm your Course is an H3. Needs to be an H2
* Title element on the page is "choose your track," when it should be "confirm your course."
* Modal is not responsive. It should function and look like the other modals in this flow (e.g., Terms of Service or data sharing consent, but even these do not look alike).

**JIRA:** [ENT-450](https://openedx.atlassian.net/browse/ENT-450)

**Dependencies:** N/A

**Merge deadline:** 30 June, 2017

**Installation instructions:** Install `edx-enterprise` from this branch `zub/ENT-450-enterprise-landing-page-styling-feedback` in `edx-platform`.

**Testing instructions:**

1. Go to enterprise customers django admin at `admin/enterprise/enterprisecustomer/`
2. Add enterprise customer with logo and with consent enabled with option `At Enrollment` and link it with an `idp`.
3. Create/publish a course in studio and create related modes in Ecom course admin tool.
4. As an anonymous user view the enterprise landing page for the enterprise course by accessing the enterprise course enrollment url with enterprise customer uuid from step no 2, e.g: http://zubair.localhost:8000/enterprise/72416e52-8c77-4860-9584-15e5b06220fb/course/course-v1:edX+TEST_01+2016_R1/enroll/
5. The learner will be redirected to `idp` login page related to the enterprise and on successful login learner will be able view enterprise landing page after linking the edX account with enterprise.
6. Verify that `Welcome to edX.` is now showing in left panel.
7. Verify that clicking on link `View Course Details` opens course details modal which is identical to DSC decline modal.

**Merge checklist:**

- [ ] Regenerate requirements with `make upgrade && make requirements` (and make sure to fix any errors).
  **DO NOT** just add dependencies to `requirements/*.txt` files.
- [ ] All reviewers approved
- [x] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are (reasonably) squashed
- [ ] Translations are updated
- [ ] PR author is listed in AUTHORS

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

### CODE REVIEW

**Comment by zubair-arbi** [comment]
Here is the sandbox link: https://enterprise.sandbox.edx.org/enterprise/e78b4a36-d900-4c4e-90b5-d1af4c4380aa/course/course-v1:edX+DemoX+Demo_Course/enroll/

**Comment by brittneyexline** [comment]
I'm getting some weird behavior with the sandbox - if I try to visit the link subsequent times, after clicking sign in through testshib it takes me to the non branded sign in page... this behavior also doesn't seem related to your changes so I'm not sure what's going on.

**Comment by douglashall** [comment]
@zubair-arbi I have cherry-picked this commit onto a sprint branch (edx/edx-enterprise:mighty_mouse) and deployed that branch to https://business.sandbox.edx.org.

**Comment by brittneyexline** [comment]
I've rebased this and fixed one issue that I saw - but it would be good to get at least one approval from someone else before merging.

**Comment by douglashall** [comment]
@brittneyexline I deployed the latest to the sandbox. It looks like the modal still isn't quite responsive and there is some double-scrolling going on.

Should we merge this and create a follow up ticket to address consistency and responsiveness in all modals?

**Comment by brittneyexline** [comment]
Squashed from https://github.com/edx/edx-enterprise/pull/138/commits/015e310cf948dd624068d20109e39604548de5ec. I filed https://openedx.atlassian.net/browse/ENT-489 as a follow up for making the modals more consistent and responsive.

**Pull request merged**
