### PR TITLE
[ENT-157] Reconfigure isort linter

### PR DESCRIPTION
**Pull request by replaceafill**
**Description:** This PR sets the isort linter to use the [Vertical Hanging Indent mode](https://github.com/timothycrosley/isort#multi-line-output-modes) with trailing comma support to make imports easier to insert and review.

**JIRA:** [ENT-157](https://openedx.atlassian.net/browse/ENT-157)

**Dependencies:** None

**Testing instructions:**

1. Check out this branch.
2. Run `make quality` and verify that the isort command (commands[12]) succeeds.
3. Optionally you can run `make test-all` to verify the whole suite passes.

**Merge checklist:**

- [x] Regenerate requirements with `make upgrade && make requirements` (and make sure to fix any errors).
  **DO NOT** just add dependencies to `requirements/*.txt` files.
- [x] All reviewers approved
- [X] CI build is green
- [X] Version bumped
- [X] Changelog record added
- [X] Documentation updated (not only docstrings)
- [X] Commits are (reasonably) squashed
- [X] Translations are updated
- [X] PR author is listed in AUTHORS

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is finished.
- [ ] Delete working branch (if not needed anymore)

**Reviewers:**
- [ ] @haikuginger

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @replaceafill! I've created [OSPR-1743](https://openedx.atlassian.net/browse/OSPR-1743) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-enterprise/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by haikuginger** [comment]
@replaceafill, looks good to me, so I've tagged some additional reviewers. Once you've got two more approvals, go ahead and follow the merge checklist, asking me any questions you need answered, and ping me that you're ready for merge.

**Comment by haikuginger** [comment]
@replaceafill, as with your last PR, please go ahead and proceed through the merge checklist and ping me when complete or with any questions.

**Comment by replaceafill** [comment]
@haikuginger Done with the merge checklist. Let me know if I missed anything, and thank you for the help!

**Comment by haikuginger** [comment]
Thanks for the help with paying off this debt, @replaceafill!

**Pull request merged**
