### PR TITLE
Increase font size on DSC page.

### PR DESCRIPTION
**Pull request by mtyaka**
**Description:** The default font size at edX is 16px for readability, but DSC page was using 14px. This patch updates DSC font size to 16px.

**JIRA:** [ENT-764](https://openedx.atlassian.net/browse/ENT-764)

**Testing instructions:**

1. Log in as an enterprise user.
2. Go to a course which requires data sharing consent to view the DSC page.
3. Verify that the paragraph font size is 16px.

**Merge checklist:**

- [x] Check that the versions of the requirements in the `platform-master.in` file match edx-platform.
- [x] New requirements are in the right place (`base.in` if only used in enterprise; in the correct `platform-****.in` files if they're hosted in edx-platform)
- [x] Regenerate requirements with `make upgrade && make requirements` (and make sure to fix any errors).
  **DO NOT** just add dependencies to `requirements/*.txt` files.
- [x] Called `make static` for webpack bundling if any static content was updated.
- [x] All reviewers approved
- [ ] CI build is green
- [x] Version bumped
- [x] Changelog record added
- [x] Documentation updated (not only docstrings)
- [x] Commits are (reasonably) squashed
- [x] Translations are updated
- [x] PR author is listed in AUTHORS

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is finished.
- [ ] Delete working branch (if not needed anymore)
- [ ] edx-platform PR (be sure to include edx-platform requirements upgrades that were present in this PR)

**Author notes and concerns**:

There's a [CSS rule which sets default font-size to 14px on all enterprise pages](https://github.com/edx/edx-enterprise/blob/f231808af6cb2c177989701fc78382348e3c2a6b/enterprise/static/enterprise/sass/_base.scss#L84-L86). I tried removing it, but that causes some layout issues on course and program landing pages, so I decided to override the default font size for the DSC page instead since ENT-764 is explicitly about the DSC page.

If desired, I could remove that global enterprise default and try to fix layout issues on other enterprise pages instead.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @mtyaka! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fedx-enterprise&number=250"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by mtyaka** [comment]
**Screnshot before**:

screen shot 2017-11-28 at 08 34 34

**Screenshot after**:

screen shot 2017-11-28 at 08 34 18

**Comment by UmanShahzad** [comment]
This is now on the sandbox.

**Comment by UmanShahzad** [comment]
@mtyaka Good to merge after changelog/bump, etc..

**Comment by mtyaka** [comment]
Rebased from f231808af6cb2c177989701fc78382348e3c2a6b.

**Pull request merged**
