### PR TITLE
Link enrollment template to enterprise instead of site

### PR DESCRIPTION
**Pull request by tuchfarber**
NOTE: This was previously approved and merged here: https://github.com/edx/edx-enterprise/commit/d4ee2525d5051dbbae51bc320d88f556f43f7ae2, I accidently merged before editing information, so this is a new PR to merge with that information added (version number and changelog)

Step 1 in a 3 step deployment.

**Description:** Describe in a couple of sentence what this PR adds
First step in making the email notification template attached to the enterprise instead of the site. This makes the site field nullable, adds the enterprise_customer field, and changes all tests to reference the new field. I have verified that this is NOT being used in prod or stage currently.

**JIRA:** Link to JIRA ticket
[WL-1240]

**Dependencies:** dependencies on other outstanding PRs, issues, etc. 
No dependencies. Will need two follow up PRs (removing field from model, running removal migration)

**Merge deadline:** List merge deadline (if any)
N/A

**Installation instructions:** List any non-trivial installation 
instructions.
N/A

**Testing instructions:**
(Available on the WL sandbox right now)

1. Add enrollment notification email template in django admin
2. See that it attaches to enterprise customer instead of site.

**Merge checklist:**

- [ ] Check that the versions of the requirements in the `platform-master.in` file match edx-platform.
- [ ] New requirements are in the right place (`base.in` if only used in enterprise; in the correct `platform-****.in` files if they're hosted in edx-platform)
- [ ] Regenerate requirements with `make upgrade && make requirements` (and make sure to fix any errors).
  **DO NOT** just add dependencies to `requirements/*.txt` files.
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are (reasonably) squashed
- [ ] Translations are updated
- [ ] PR author is listed in AUTHORS

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is finished.
- [ ] Delete working branch (if not needed anymore)
- [ ] edx-platform PR (be sure to include edx-platform requirements upgrades that were present in this PR)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

### CODE REVIEW

**Comment by tuchfarber** [comment]
@douglashall  If you get a minute, could you take a look at that quality test it's failing? The imports are in the exact same order as #199 and that one passed.

**Comment by UmanShahzad** [comment]
@tuchfarber Just try `pip install . && make isort` and see if it fixes the problem (I say do `pip install .` first because it ensures you've installed enterprise, otherwise `isort` misbehaves).

**Comment by UmanShahzad** [comment]
@tuchfarber Bahaha, I cannot believe that was the reason :)

**Comment by tuchfarber** [comment]
Thanks for the tip @UmanShahzad. That worked! No idea how a blank line at the end of a file causes an import sorting error...

**Comment by UmanShahzad** [comment]
@tuchfarber Yeah it's quite unexpected :P

Your build was stuck so I restarted the relevant parts. Let's merge it then make the bump PR.

**Comment by UmanShahzad** [comment]
Ugh, sorry, I over-eagerly merged this without waiting for you to squash. Whatever... next time will watch out.

**Pull request merged**
