### PR TITLE
Use LMS_INTERNAL_ROOT_URL as api base url.

### PR DESCRIPTION
**Pull request by mtyaka**
**Description:**

`LMS_ROOT_URL` is the publicly accessible url, and it is not always what you want to use for internal communication. This PR uses `LMS_INTERNAL_ROOT_URL` instead. Support for `LMS_INTERNAL_ROOT_URL` is being added in https://github.com/edx/edx-platform/pull/16510.

**Dependencies:**

- https://github.com/edx/edx-platform/pull/16510
- https://github.com/edx/configuration/pull/4200

**Testing instructions:**

Follow testing instructions in https://github.com/edx/edx-platform/pull/16510.

**Merge checklist:**

- [ ] Check that the versions of the requirements in the `platform-master.in` file match edx-platform.
- [x] New requirements are in the right place (`base.in` if only used in enterprise; in the correct `platform-****.in` files if they're hosted in edx-platform)
- [x] Regenerate requirements with `make upgrade && make requirements` (and make sure to fix any errors).
  **DO NOT** just add dependencies to `requirements/*.txt` files.
- [ ] Called `make static` for webpack bundling if any static content was updated.
- [x] All reviewers approved
- [ ] CI build is green
- [x] Version bumped
- [x] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [x] Commits are (reasonably) squashed
- [ ] Translations are updated
- [x] PR author is listed in AUTHORS

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is finished.
- [ ] Delete working branch (if not needed anymore)
- [ ] edx-platform PR (be sure to include edx-platform requirements upgrades that were present in this PR)

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @mtyaka! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=240&repo=edx%2Fedx-enterprise"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by UmanShahzad** [comment]
:+1:

- [x] I tested this: Followed testing instructions. Also tried multiple flows and different APIs to ensure things still work. I also tried the manage learners admin page to make sure client-facing code that calls APIs still works.
- [x] I read through the code
- [x] I checked for accessibility issues
- [x] Includes documentation

**Comment by mtyaka** [comment]
Rebased from 36ef9e7e984a7365fc690dfc550b3825017b2896.

**Comment by mtyaka** [comment]
Thanks @UmanShahzad !

@brittneyexline or @douglashall Can you review this please?

**Comment by mtyaka** [comment]
Rebased from df857912228260d10fa9b1d1607165281b46d143.

**Pull request merged**
