### PR TITLE
[ENT-996] Remove unique constraints on reporting config.

### PR DESCRIPTION
**Pull request by UmanShahzad**
There seems to be no reason to actually have them. To quote myself:

> The Enterprise Customer used to be one-to-one to a reporting config, but later I switched it to be one-to-many instead because we should be able to have multiple data/report types per customer. However I thought there was a good reason to have a 1-to-1 relationship in the first place so I added the constraint on enterprise_customer to respect whatever reason that was. In hindsight there doesn't seem to be a good reason since we can still make multiple reporting configs per customer anyway...

**JIRA:** https://openedx.atlassian.net/browse/ENT-996

**Dependencies:** None.

**Merge deadline:** Whenever.

**Testing instructions:**

1. Run migrations with this in place.
2. Ensure you can add reporting configurations for the same customer as your heart desires.

**Merge checklist:**

- [ ] Check that the versions of the requirements in the `platform-master.in` file match edx-platform.
- [ ] New requirements are in the right place (`base.in` if only used in enterprise; in the correct `platform-****.in` files if they're hosted in edx-platform)
- [ ] Regenerate requirements with `make upgrade && make requirements` (and make sure to fix any errors).
  **DO NOT** just add dependencies to `requirements/*.txt` files.
- [ ] Called `make static` for webpack bundling if any static content was updated.
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are (reasonably) squashed
- [ ] Translations are updated
- [ ] PR author is listed in AUTHORS

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is finished.
- [ ] Delete working branch (if not needed anymore)
- [ ] edx-platform PR (be sure to include edx-platform requirements upgrades that were present in this PR)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @UmanShahzad! I've created [OSPR-2416](https://openedx.atlassian.net/browse/OSPR-2416) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-enterprise/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by UmanShahzad** [comment]
@georgebabey Thanks! I've version bumped and squashed, and will make a PR on edx-platform soon.

**Comment by UmanShahzad** [comment]
Actually I might make the PR to edx-platform tomorrow, we may have already missed trying to get it into stage today.

**Comment by edx-webhook** [comment]
@UmanShahzad 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-enterprise&entry.867055334=https://github.com/edx/edx-enterprise/pull/314&entry.1484655318=https://github.com/UmanShahzad&entry.752974735=2018-05-16+19:29&entry.1917517419=2018-05-16+19:59&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by UmanShahzad** [comment]
FYI https://github.com/edx/edx-platform/pull/18214#issuecomment-389658354 -- I can just manually update edx-enterprise but let's see if we can sort it out properly first.

**Comment by edx-webhook** [comment]
Although this pull request is already merged, I've created [OSPR-5534](https://openedx.atlassian.net/browse/OSPR-5534) so that we can track it in Jira.

There is nothing you have to do. No action is needed from your side.  Thanks again for your contribution.

**Pull request merged**
