### PR TITLE
[ENT-300] Data Sharing Consent: Expand Arrow off by a couple pixels

### PR DESCRIPTION
**Pull request by replaceafill**
**Description:** This PR fixes the CSS for the expand arrow in the data sharing consent page.

**JIRA:** [ENT-300](https://openedx.atlassian.net/browse/ENT-300)

**Dependencies:** None

**Installation instructions:** Basic enterprise installation

**Testing instructions:**

1. Set up an EnterpriseCustomer, enable data sharing consent, and set the consent requirement level to "at login".
2. Add a user to the EnterpriseCustomer using the Manage Learners admin panel.
3. Log in as the learner and you'll be redirected to the data sharing consent page.
4. Click the arrow in the Data Sharing Policy bar.
5. Verify that once the policy is displayed the arrow doesn't look like this:

before

**Merge checklist:**

- [x] Regenerate requirements with `make upgrade && make requirements` (and make sure to fix any errors).
  **DO NOT** just add dependencies to `requirements/*.txt` files.
- [x] All reviewers approved
- [X] CI build is green
- [X] Version bumped
- [X] Changelog record added
- [X] Documentation updated (not only docstrings)
- [X] Commits are (reasonably) squashed
- [X] Translations are updated
- [X] PR author is listed in AUTHORS

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is finished.
- [ ] Delete working branch (if not needed anymore)

**Reviewers:**

- [ ] @haikuginger

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @replaceafill! I've created [OSPR-1741](https://openedx.atlassian.net/browse/OSPR-1741) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-enterprise/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by haikuginger** [comment]
Okay, @replaceafill, we've gotten approval to go ahead and merge this, so go ahead and go through the "merge checklist", and ping me when you're done. I'll take care of the actual merge and the post-merge steps. You can skip the dependency regeneration steps, since we didn't update any dependencies as part of this PR.

**Comment by haikuginger** [comment]
@replaceafill, note that the master branch is now up to [0.33.2](https://github.com/edx/edx-enterprise/blob/master/enterprise/__init__.py#L7), so you'll need to rebase on master before adding your changelog and version bump. :)

**Comment by replaceafill** [comment]
@haikuginger Yeah I noted it a bit late :( But I think it's ready. Let me know if I missed anything.

**Comment by haikuginger** [comment]
Thanks for the great work @replaceafill!

**Pull request merged**
