### PR TITLE
Updated isort

### PR DESCRIPTION
**Pull request by ziafazal**
**Description:** This PR updates isort package to it latest version(4.3.4) and sorts order of imports using it.

**Merge checklist:**

- [x] New requirements are in the right place (`base.in` if only used in enterprise; in the correct `platform-****.in` files if they're hosted in edx-platform)
- [x] Regenerate requirements with `make upgrade && make requirements` (and make sure to fix any errors).
  **DO NOT** just add dependencies to `requirements/*.txt` files.
- [ ] All reviewers approved
- [x] CI build is green
- [ ] Version bumped
- [x] Changelog record added
- [x] Commits are (reasonably) squashed
- [x] PR author is listed in AUTHORS

**Post merge:**
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

### CODE REVIEW

**Comment by georgebabey** [comment]
@ziafazal Please note the isort config we use is in our [tox.ini file](https://github.com/edx/edx-enterprise/blob/master/tox.ini#L34) so if you run isort globally you'll get a different result than from within tox.

You'll want to either run `make validate` or run isort within the .tox/ folder  There is no need to change all of the import ordering

**Comment by ziafazal** [comment]
@georgebabey Thanks for the info. It appears new version of `isort` treats `consent` and `integrated` apps as first party apps instead of third party apps and that is in fact true. This PR has imports sorted that way by `isort`. Could you please review?

**Comment by georgebabey** [comment]
@ziafazal That's probably due to the change in tox.ini here - https://github.com/edx/edx-enterprise/pull/298/files#diff-b91f3d5bd63fcd17221b267e851608e8R39  But I agree those should be first party. Thanks for updating!

**Comment by ziafazal** [comment]
@bill-filler can you review this too?. It appears I need 2 thumbs up to before merging it.

**Pull request merged**
